title: Duffau's Blog
author: Christian Duffau-Rasmussen
description: >-
  A blog accumulating stray thoughts mostly circling 
  around statistics, probability theory, 
  machine learning and the like. 

github_username:  duffau
linkedin_username: christian-duffau-rasmussen

# Build settings
theme: minima
domain: duffau.github.io       
url: https://duffau.github.io
baseurl: /blog/

lsi: false
safe: true

source: .
incremental: false

highlighter: rouge
gist:
  noscript: false

plugins:
  - jekyll-seo-tag

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - .venv/
  - "*.py"
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Makefile

# ----------------------
# Dependencies versions
# ----------------------

mathjax:
  version: "3.2.0"
