PYTHON=.venv/bin/python3

calc:
	$(PYTHON) calc_kinds_prob.py
	$(PYTHON) calc_dice_count_permutations.py

plot:
	$(PYTHON) plot_dice_count_permutations.py
	$(PYTHON) plot_dynamic_prog_perm_illustration.py
	$(PYTHON) plot_kinds_prob.py
	$(PYTHON) plot_median.py
	$(PYTHON) plot_stair_prob.py